language: python
python:
    - "2.7"
script: nosetests

# Needs openCV v2, but it's not available via pip, so...
sudo: true
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install python-dev python-numpy
before_script:
    - mkdir OpenCV
    - cd OpenCV
    - wget -O OpenCV-2.4.10.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.10/opencv-2.4.10.zip/download
    - unzip OpenCV-2.4.10.zip
    - cd opencv-2.4.10
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -D CUDA_ARCH_BIN=3.2 -D CUDA_ARCH_PTX=3.2 -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D BUILD_TIFF=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
    - make -j
    - sudo make install
    - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
    - sudo ldconfig
    - cd ../../..
