language: python
python:
    - "2.7"
script: nosetests

# Needs openCV v2, but it's not available via pip, so...
sudo: true
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install python-dev python-numpy
before_script:
    - git clone -b 2.4 https://github.com/Itseez/opencv.git
    - cd opencv
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make
    - sudo make install
    - cd ../..
    - ls /usr/local
    - ls /usr/local/lib
    - export
    - export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
