language: python
python:
    - "2.7"
script: nosetests

# Needs openCV, but it's not available via pip, so...
sudo: true
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install python-dev python-numpy
before_script:
    - git clone https://github.com/Itseez/opencv.git
    - cd opencv
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make
    - sudo make install
    - cd ../..
